name: flutter_trivia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  html_unescape: ^2.0.0
  audioplayers: ^5.2.1
  http: ^0.13.6
  shared_preferences: ^2.0.15
  flutter_svg: ^2.0.7
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    -  assets/trivia_test.json
    -  assets/sounds/correctAnswer.mp3
    -  assets/sounds/incorrectAnswer.mp3
    -  assets/images/chiliPepperVector.svg
